INSERT INTO USERS (ID, LOGIN, PASSWORD, WALLET)
VALUES (1, 'dima', '$2a$10$cT0bO8otXAxuDk1lRevmVOtR2mGzXimRhxKWbEfw9JjvCmFUvTn8K', 25);
INSERT INTO USERS (ID, LOGIN, PASSWORD, WALLET)
VALUES (2, 'john', '$2a$10$7pR5qFVfWQFnjGq2vkIeeOj9fomccRjogQtNonCv736pXjL3zFFtO', 10);

INSERT INTO PRODUCTS (ID, CREATION_TIME, NAME, PRICE, STOCK)
VALUES (1, '2020-11-07', 'Apple', 5, 10);
INSERT INTO PRODUCTS (ID, CREATION_TIME, NAME, PRICE, STOCK)
VALUES (2, '2020-11-07', 'Milk', 8, 15);
INSERT INTO PRODUCTS (ID, CREATION_TIME, NAME, PRICE, STOCK)
VALUES (3, '2020-11-07', 'Bread', 3, 20);

INSERT INTO USERS_PRODUCTS(USER_ID, PRODUCT_ID, QUANTITY)
VALUES (1, 1, 1);
INSERT INTO USERS_PRODUCTS(USER_ID, PRODUCT_ID, QUANTITY)
VALUES (1, 3, 1);
INSERT INTO USERS_PRODUCTS(USER_ID, PRODUCT_ID, QUANTITY)
VALUES (2, 3, 1);
INSERT INTO USERS_PRODUCTS(USER_ID, PRODUCT_ID, QUANTITY)
VALUES (2, 2, 1);